---
- name: setup Aprofile bastion Host
  hosts: Localhost
  connection: Localhost
  gather_facts: no
  tasks:
    - name: Import VPC setup variable
      include_vars: vars/bastion_setup
      
    - name: Import VPC setup variable
      include_vars: vars/output_cars
      
    - name: Create Aprofile ec2 key
      ec2_key:
        name: Aprofile-key
        regison: "{{ region }}"
      register: key_out
      
    - name: Save private Key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
        when: key_out.changed
        
    - name: Create Sec Grp for bastion Host
      ec2_group:
        name: Bastion-host-sg
        description: Allow post 22 from everywhere and all post within sg
        region: "{{region}}"
        vpc_id: '{{vpcid}}"
        rules:
          - proto: top
            from port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
        register: BastionSG_out
        
    - Creating Bastion Host
      ec2:
        key name: Aprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host"
          Project: Aprofile
          Owner: Devops team
        exact_count: 1
        count_tag:
          Name: "Bastion_Host"
          Project: Aprofile
          Owner: Devops team
        group_id: "{{BastionSG_out.group_id}}"
      register: bastionHost_out